### ISSUE TITLE
Automatic checks fail because network 1.14.0 not yet on CRAN

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm.ego#10]
Is the version restriction in `DESCRIPTION` on `master` branch required by the code as on `master`?

**Comment by krivit** [comment]
I don't remember, off the top of my head, but the solution is probably to add an
```
r_github_packages:
- statnet/network
```
directive.

**Comment by mbojan** [comment]
I'll try that.

**Comment by krivit** [comment]
Looks like they work now.
