### ISSUE TITLE
change "vertex.names" to "ego.id"?

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm.ego#11]
1. names are not necessarily unique, IDs are
2. used in the context of the alter list, "vertex" could refer to either ego or alter

this may no longer be relevant with the switch to egoR.  if so, just lmk and close this.

**Comment by krivit** [comment]
It's a matter of consistency between the network and the ego dataset.

**Comment by martinamorris** [comment]
i'm not sure i understand what you're saying.

there is no vertex attribute called "vertex.name" in the original 
faux.mesa.high network object.


On Wed, 27 Sep 2017, Pavel N. Krivitsky wrote:

> 
> It's a matter of consistency between the network and the ego dataset.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[AH0J4nmxvO9OFQRcRx1m4AzNZ5k74UAjks5smsuWgaJpZM4PmTqW.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by krivit** [comment]
Faux Mesa High doesn't have a `vertex.names` attribute; but when networks do have that attribute, it's usually a unique node identifier. We could rename it to something else when converting, but that would make it inconsistent with the network object.

In any case, you're right: it's largely moot, since in `egor`, it's just another ego column.
