### ISSUE TITLE
Should we suppress the ergm estimation message for the degreedist.egodata function?

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm.ego#12]
currently, the degreedist.egodata function prints out the ergm model fitting message when <brg=T> is specified.

this seems unnecessary -- the info is not useful -- and it could lead to confusion among users, since they have not explicitly made a call to ergm.

**Comment by martinamorris** [comment]
Pavel, did you close this because you don't agree, or b/c you made the change?

**Comment by mbojan** [comment]
It's fixed @martinamorris

**Comment by martinamorris** [comment]
> It's fixed @martinamorris

k, thx.  usually there's a link included to the commit

**Comment by krivit** [comment]
> k, thx.  usually there's a link included to the commit

I had forgotten to mention the issue it in the commit, so I had linked to the commit in the closing message instead.

**Comment by martinamorris** [comment]
> I had forgotten to mention the issue it in the commit, so I had linked to the commit in the closing message instead.

dang, did i just miss that?  i could swear there wasn't a commit # 
reference in the closing message when i looked earlier.  sorry if i just 
missed it...

**Comment by krivit** [comment]
It's this one:
> krivit closed this in 4ef757b 11 days ago

The string of hex characters is the commit ID that fixed it.
