### ISSUE TITLE
Do the same attributes need to be assigned to both egos and alters, and do they need to be named the same thing?

### ISSUE THREAD

**Issue by sumich** [statnet/ergm.ego#15]

**Comment by krivit** [comment]
At this time, yes. This may change in the near future.

**Comment by sumich** [comment]
If I have more attributes for my egos than my alters and I would like to include them, can I include the same the extra attributes that I have for my egos as variables for my alters but keep the variables blank? Since this analysis is specifically for ego networks will the analysis still be able to work with that information.

**Comment by krivit** [comment]
At this time, no. We are working on it.
