### ISSUE TITLE
could not find function "degreedist.egodata"

### ISSUE THREAD

**Issue by shangyuan232** [statnet/ergm.ego#20]
cdrHyper.ego is a egodata abject. when running degreedist.egodata, it shows the following error:

> > degreedist.egodata(cdrHyper.ego)
Error in degreedist.egodata(cdrHyper.ego) : 
  could not find function "degreedist.egodata"

**Comment by krivit** [comment]
Does just `degreedist(cdrHyper.ego)` work?

**Comment by krivit** [comment]
Basically `degreedist()` is now a generic exported by `ergm`, so `ergm.ego` just implements an `egodata` method for it.

**Comment by martinamorris** [comment]
nice :)
