### ISSUE TITLE
Additional ergm terms abbsdiffby

### ISSUE THREAD

**Issue by dth2** [statnet/ergm.ego#38]
Does ergm.ego need custom versions of each ergm term?  Sam has written up an ergm term, absdiffby, for targeting age homophily by sex, but when I try to use it with an ergm.ego call I get:

Error in EgoStat.absdiffby(egodata = structure(list(egos = structure(list( : 
  could not find function "EgoStat.absdiffby"

I think this a going to be a fairly standard term used for modeling heterosexuals so it would be helpful if it worked with ergm.ego.

**Comment by krivit** [comment]
Yes, it needs an `EgoStat` for every term. I am looking at some algorithmic improvements that eliminate this need, but it'll be a while before I'll have time to work on this.

**Comment by krivit** [comment]
@dth2 , @martinamorris , do we want to get this into the 3.6 release?

**Comment by sgoodreau** [comment]
@smjenness has added this term into EpiModel, and my understanding is that it uses different arguments than the version we wee planning for ergm (and which I had in evonet).  So if we do add it as it, we might create additional downstream issues.  @smjenness  can you clarify? One option may be simply to give it a slightly different name.

**Comment by dth2** [comment]
Yes I think we need this if possible.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by krivit** [comment]
Ah, I thought that it was already in `ergm`. If it's not, then it shouldn't be in `ergm.ego`, either. The `EgoStat` should then be implemented in `EpiModel`.

**Comment by sgoodreau** [comment]
maybe I have it wrong and it's in ergm, not Epimodel.

**Comment by martinamorris** [comment]
It's not in `ergm`.

@krivit, will it be possible to use the operator terms in 4.0 to produce an absdiff by attribute (or mixingmatrix by attribute)?  i confess i still don't fully understand this new interface.

**Comment by krivit** [comment]
I think so, by interacting `absdiff` with appropriate nodal or dyadic covariates or filtering on them. Though, we need to think through operator `EgoStats` as well.

**Comment by krivit** [comment]
In any case, the term probably shouldn't be in `ergm.ego` but closer to where its `InitErgmTerm` counterpart is defined, so I am going to close this.
