### ISSUE TITLE
typo in control.ergm.ego.rd?

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm.ego#39]
I think the line below should refer to ppopsize, right? :

https://github.com/statnet/ergm.ego/blob/a8f633e9dbaaccf8ec051802f83679f6d18508d4/man/control.ergm.ego.Rd#L14

Happy to make the change, just wanted to make sure first.

**Comment by krivit** [comment]
Yes, it should. Thanks!

**Comment by martinamorris** [comment]
Done.  I used the instructions for updating the public and private branches (for the first time).  You might want to take a look to make sure I did it correctly :)

**Comment by krivit** [comment]
Looks like it. Thanks!
