### ISSUE TITLE
Fix class of object returned by mixingmatrix method

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm.ego#54]
As per statnet/network#32.

**Comment by krivit** [comment]
Was this ever merged into `master`?

**Comment by mbojan** [comment]
I hoped to address #54 and #55 in one go, but let's make smaller steps instead...

**Comment by krivit** [comment]
Well, if this doesn't get resolved in the next day or two, it's not going into 0.9, since the workshop is in 10 days.

**Comment by mbojan** [comment]
The merge leads to several conflicts. It was not clear to me why. I'll try before the release. Otherwise next cycle.

**Comment by krivit** [comment]
Thanks! Maybe make a PR so that I could take a look as well?

**Comment by mbojan** [comment]
It seems I fixed #54 (which is trivial) on the branch but did not merge/PR it because of the conflicts. I guess they are because of the grand merge that happen in the mean time. 

I'll have a look in 12hrs. I will add you @krivit to my fork so you can have a look (just in case). There are two branches `i54-*` and `i55-*`.
