### ISSUE TITLE
update ergm.ego workshop

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm.ego#60]
see:

https://github.com/krivit/ergm.ego-papers/blob/master/resources/Sunbelt_tutorial/ergm.ego_tutorial.Rmd

**Comment by krivit** [comment]
@martinamorris , what's the situation? I would like to push `ergm.ego` in the next day or two; are any changes needed for the sake of the workshop?

**Comment by krivit** [comment]
Since we've successfully taught the workshop, I'm going to call this one completed.
