### ISSUE TITLE
change name of degreedist function?

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm.ego#66]
since it produces a plot, can we rename this plot.degdist?

**Comment by krivit** [comment]
It also outputs the degree distribution in the same format as the `network` function. If we want consistency, it might be better to make `plot=FALSE` by default.

**Comment by martinamorris** [comment]
ah, ok .  i missed that from the Rmd chunk eval.  maybe then it is worth making `plot=F` by default.

and do you mean the `network::degreedist` function?

**Comment by krivit** [comment]
My bad. `degreedist` is from `ergm`. `mixingmatrix` is from `network`.
