### ISSUE TITLE
`data("fmhfit")`

### ISSUE THREAD

**Issue by romainfrancois** [statnet/ergm.ego#72]
We're in the process of releasing dplyr 1.0.8 and our revdep checks have picked up this potential problem, which however feels unrelated to dplyr: 

```
W  checking contents of ‘data’ directory (3.9s)
   Output for data("fmhfit", package = "ergm.ego"):
     Search path was changed
```

I'm not sure what is the problem though. The error comes from this function that is run as part of `R CMD check` : 

```r
.check_package_datasets2 <-
function(fileName, pkgname)
{
    oldSearch <- search()
    dataEnv <- new.env(hash = TRUE)
    suppressMessages(utils::data(list = fileName, package = pkgname,
                                 envir = dataEnv))
    if (!length((ls(dataEnv)))) message("No dataset created in 'envir'")
    if (!identical(search(), oldSearch)) message("Search path was changed")
    invisible(NULL)
}
```

**Comment by mbojan** [comment]
Thanks @romainfrancois. Does making the data loading lazy solve it? That would be strange indeed...

**Comment by romainfrancois** [comment]
yeah, #73 solves this for some reason

**Comment by mbojan** [comment]
The package passes all the checks on all platforms without it. Is it possible that some thing is not right with your revdep testing infrastructure?

**Comment by mbojan** [comment]
@romainfrancois I'll try to have a look myself. Where's the dplyr version you are planning to release? rstudio/dplyr@master?

**Comment by romainfrancois** [comment]
yeah, except the default branch is now `main`, you can get it with: `pak::pkg_install("tidyverse/dplyr")`

**Comment by mbojan** [comment]
Thanks.

PS. So is `remotes::install_github()` falling out of favor? ;-)

**Comment by romainfrancois** [comment]
They serve different purpose, `pak::pak()` is more for interactive use, and `remotes` for use in e.g. GitHub actions

**Comment by mbojan** [comment]
OK, thanks. I have some difficulties with getting the dev version of `dplyr` to work, so perhaps I'll just merge it...
