### ISSUE TITLE
Maintainer address no longer works

### ISSUE THREAD

**Issue by kurthornik** [statnet/ergm.ego#85]
Yesterday the CRAN team tried reporting an issue, getting

<pavel@statnet.org>: host fwd2.porkbun.com[52.10.201.111] said: 554 5.7.1
    <pavel@statnet.org>: Relay access denied (in reply to RCPT TO command)

Can you please fix as necessary?

**Comment by krivit** [comment]
Sorry about that! Working on it!

**Comment by krivit** [comment]
Should be fixed now. Thanks for flagging it!

**Comment by kurthornik** [comment]
Thanks!
Best
-k
